/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cg;

import org.junit.Test;

import com.cg.EmployeePayrollService;

import static org.junit.Assert.*;

public class EmployeePayrollTest {
    
}
